default_config:
system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
ios: !include ios_settings.yaml
mobile_app:
frontend:
  themes: !include_dir_merge_named themes
switch: !include switches.yaml
# python_script:
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate
hacs:
  token: !secret hacs_token
group: !include groups.yaml
script: !include_dir_named scripts/
scene: !include_dir_merge_list scenes 

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret_id

sensor: !include_dir_merge_list sensors/
input_boolean: !include_dir_named input_boolean/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
input_text: !include_dir_named  input_text/
input_datetime: !include_dir_named input_datetime/
light: !include_dir_merge_list lights 

automation: !include automations.yaml
automation old: !include_dir_merge_list automations

#Google calendar
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

webostv:
  host: !secret bedroom_tv_ip
  name: Bedroom TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret bedroom_tv_mac_address
  customize:
    sources:
      - youtube
      - netflix
      - eon

media_player:
notify:

adaptive_lighting:
  - name: "Circadian Lightning"
    lights: group.livingroom_adaptive_lights
    prefer_rgb_color: false
    transition: 45
    initial_transition: 1
    interval: 90
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1000
    # sunrise_time: "08:00:00"  # override the sunrise time
    # sunrise_offset:
    # sunset_time:
    # sunset_offset: 1800  # in seconds or '00:15:00'
    take_over_control: true
    detect_non_ha_changes: false
    only_once: false

