- alias: 'Turn off WatchTv Activity when TV and AVR are turned off'
  trigger:
    - platform: state
      entity_id: 
        - media_player.livingroom_tv
        - media_player.avr_zone1
      to: 'off'
  action:
    - service: remote.turn_off
      entity_id: remote.harmony_hub_livingroom
      data:
          activity: "Watch TV"